FROM python:3.10-slim

# Install OpenCV dependencies (required for Linux)
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0

WORKDIR /app
COPY . /app

# Install Python requirements
RUN pip install flask flask-cors opencv-python ultralytics numpy

# Expose the Flask port
EXPOSE 5000

# Run the app
CMD ["python", "main.py"]